/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlumbingRouteImport } from './routes/plumbing'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as EstimatesIdRouteImport } from './routes/estimates.$id'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbingRoute = PlumbingRouteImport.update({
  id: '/plumbing',
  path: '/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const EstimatesIdRoute = EstimatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EstimatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/plumbing': typeof PlumbingRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/team': typeof TeamRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/plumbing': typeof PlumbingRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/team': typeof TeamRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/plumbing': typeof PlumbingRoute
  '/profile': typeof ProfileRoute
  '/showcase': typeof ShowcaseRoute
  '/team': typeof TeamRoute
  '/estimates/$id': typeof EstimatesIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/estimates'
    | '/invoices'
    | '/plumbing'
    | '/profile'
    | '/showcase'
    | '/team'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/estimates'
    | '/invoices'
    | '/plumbing'
    | '/profile'
    | '/showcase'
    | '/team'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/estimates'
    | '/invoices'
    | '/plumbing'
    | '/profile'
    | '/showcase'
    | '/team'
    | '/estimates/$id'
    | '/invoices/$id'
    | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  EstimatesRoute: typeof EstimatesRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  PlumbingRoute: typeof PlumbingRoute
  ProfileRoute: typeof ProfileRoute
  ShowcaseRoute: typeof ShowcaseRoute
  TeamRoute: typeof TeamRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbing': {
      id: '/plumbing'
      path: '/plumbing'
      fullPath: '/plumbing'
      preLoaderRoute: typeof PlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/estimates/$id': {
      id: '/estimates/$id'
      path: '/$id'
      fullPath: '/estimates/$id'
      preLoaderRoute: typeof EstimatesIdRouteImport
      parentRoute: typeof EstimatesRoute
    }
  }
}

interface EstimatesRouteChildren {
  EstimatesIdRoute: typeof EstimatesIdRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesIdRoute: EstimatesIdRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  EstimatesRoute: EstimatesRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  PlumbingRoute: PlumbingRoute,
  ProfileRoute: ProfileRoute,
  ShowcaseRoute: ShowcaseRoute,
  TeamRoute: TeamRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
